name: PerfectFlight
version: 0.0.2
main: me.stefan923.perfectflight.PerfectFlight
description: Adds a fully customizable flight system to Minecraft.
softdepend: [Factions]
authors: [Stefan923]

commands:
  perfectflight:
    description: Infos about this plugin.
    aliases: [perfectfly, pfly, pflight]
  fly:
    description: Enable/Disable own flight mode.
    aliases: []

permissions:
  perfectflight.admin:
    description: Access to powerfull commands, like reload, configuration commands.
    default: op
  perfectflight.fly:
    description: Access to use /fly command.
    default: op